import { ChangeEvent, FormEvent, useEffect, useMemo, useRef, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { io, Socket } from 'socket.io-client';
import { API_URL, api } from './api';
import { Ban, BellOff, ChevronLeft, Flag, ImagePlus, Lock, LogOut, Menu, MessageCircle, MoreVertical, Send, Settings, ShieldCheck, Trash2, Users, X } from 'lucide-react';

type Profile={nickname:string;ageRange:string;city:{name:string};cityId?:string};
type User={id:string;profile:Profile};
type Msg={id:string;content:string;createdAt:string;user:User;sender?:User;recipient?:User|null;scope?:'PUBLIC'|'RESERVED';blockedForMe?:boolean;conversationId?:string};
type Participant={userId:string;nickname:string;ageRange:string};
type Conversation={id:string;participantOneId:string;participantTwoId:string;requestedById:string;status:'PENDING'|'ACCEPTED';participantOne:User;participantTwo:User;unreadCount:number};
type Invite={conversation:Conversation;from:User};
type TempImage={id:string;url:string;kind:'public'|'reserved'|'private';roomId?:string;conversationId?:string;recipientId?:string;sender:User;createdAt:string};
type PendingImage={data:ArrayBuffer;url:string;mimeType:string;size:number};

const color=(id:string)=>`hsl(${[...id].reduce((n,c)=>n+c.charCodeAt(0),0)%360} 48% 42%)`;
const other=(conversation:Conversation,me:string)=>conversation.participantOneId===me?conversation.participantTwo:conversation.participantOne;

async function compressImage(file:File):Promise<PendingImage>{
  if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>5*1024*1024)throw new Error('Escolha JPEG, PNG ou WebP de até 5 MB.');
  const bitmap=await createImageBitmap(file,{imageOrientation:'from-image'});let scale=Math.min(1,1024/Math.max(bitmap.width,bitmap.height));let quality=.86;let blob:Blob|null=null;
  for(let attempt=0;attempt<10;attempt++){
    const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));
    canvas.getContext('2d',{alpha:false})!.drawImage(bitmap,0,0,canvas.width,canvas.height);
    blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/webp',quality));
    if(blob&&blob.size<=250*1024)break;quality=Math.max(.45,quality-.08);if(quality===.45)scale*=.85;
  }
  bitmap.close();if(!blob||blob.size>250*1024)throw new Error('Não foi possível reduzir a imagem para 250 KB.');
  return{data:await blob.arrayBuffer(),url:URL.createObjectURL(blob),mimeType:blob.type,size:blob.size};
}

export function Chat(){
  const {roomId}=useParams();const nav=useNavigate();const [me,setMe]=useState<User|null>(null);const [msgs,setMsgs]=useState<Msg[]>([]);const [privateMsgs,setPrivateMsgs]=useState<Msg[]>([]);const [people,setPeople]=useState<Participant[]>([]);const [conversations,setConversations]=useState<Conversation[]>([]);const [invites,setInvites]=useState<Invite[]>([]);const [activeConversation,setActiveConversation]=useState<Conversation|null>(null);const activeRef=useRef<Conversation|null>(null);const [reservedFor,setReservedFor]=useState<Participant|null>(null);const [menuUser,setMenuUser]=useState<Participant|null>(null);const [drawer,setDrawer]=useState(false);const [roomsDrawer,setRoomsDrawer]=useState(false);const [error,setError]=useState('');const [pending,setPending]=useState<PendingImage|null>(null);const [sendingImage,setSendingImage]=useState(false);const [images,setImages]=useState<TempImage[]>([]);const [shownBlocked,setShownBlocked]=useState<Set<string>>(new Set());const [settings,setSettings]=useState(false);const [blocked,setBlocked]=useState<{id:string;user:User}[]>([]);const sock=useRef<Socket|null>(null);const fileRef=useRef<HTMLInputElement|null>(null);
  useEffect(()=>{activeRef.current=activeConversation},[activeConversation]);
  const refreshConversations=()=>api<Conversation[]>('/private-conversations').then(setConversations).catch(()=>{});
  useEffect(()=>{if(!roomId)return;let alive=true;Promise.all([api<User>('/auth/me'),api<Msg[]>(`/rooms/${roomId}/messages`),api<Conversation[]>('/private-conversations')]).then(([u,m,c])=>{if(alive){setMe(u);setMsgs(m);setConversations(c)}}).catch(()=>nav('/entrar'));
    const s=io(API_URL,{withCredentials:true});sock.current=s;s.on('connect',()=>{setError('');s.emit('room:join',roomId,(r:{error?:string})=>r?.error&&setError(r.error))});s.on('room:message:new',(m:Msg)=>setMsgs(v=>v.some(x=>x.id===m.id)?v:[...v,m]));s.on('room:participants',setPeople);s.on('private:invite',(invite:Invite)=>{setInvites(v=>[...v.filter(x=>x.conversation.id!==invite.conversation.id),invite]);refreshConversations()});s.on('private:invite:accepted',refreshConversations);s.on('private:invite:rejected',refreshConversations);s.on('private:message:new',(m:Msg)=>{setPrivateMsgs(v=>activeRef.current?.id===m.conversationId?[...v,m]:v);refreshConversations()});s.on('image:new',(event:{id:string;data:ArrayBuffer|Uint8Array;mimeType:string;kind:TempImage['kind'];roomId?:string;conversationId?:string;recipientId?:string;sender:User;createdAt:string})=>{const blob=new Blob([event.data as BlobPart],{type:event.mimeType});setImages(v=>[...v,{...event,url:URL.createObjectURL(blob)}])});s.on('disconnect',()=>setError('Reconectando…'));return()=>{alive=false;s.disconnect();sock.current=null}},[roomId,nav]);
  const currentMessages=activeConversation?privateMsgs:msgs;const currentImages=images.filter(image=>activeConversation?image.kind==='private'&&image.conversationId===activeConversation.id:image.kind!=='private'&&image.roomId===roomId);

  async function selectConversation(conversation:Conversation){if(conversation.status!=='ACCEPTED')return;setReservedFor(null);setActiveConversation(conversation);setPrivateMsgs(await api<Msg[]>(`/private-conversations/${conversation.id}/messages`));sock.current?.emit('private:join',conversation.id,(r:{error?:string})=>r?.error&&setError(r.error));setConversations(v=>v.map(c=>c.id===conversation.id?{...c,unreadCount:0}:c));}
  function send(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;const content=String(new FormData(form).get('message')??'');if(!content.trim())return;const event=activeConversation?'private:message':'room:message';const payload=activeConversation?{conversationId:activeConversation.id,content}:{roomId,content,recipientId:reservedFor?.userId};sock.current?.emit(event,payload,(r:{error?:string})=>{if(r?.error)setError(r.error);else form.reset()})}
  async function chooseImage(e:ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];e.target.value='';if(!file)return;try{if(pending)URL.revokeObjectURL(pending.url);setPending(await compressImage(file));setError('')}catch(err){setError(err instanceof Error?err.message:'Imagem inválida.')}}
  function sendImage(){if(!pending)return;setSendingImage(true);const payload=activeConversation?{kind:'private',conversationId:activeConversation.id,data:pending.data}:{kind:reservedFor?'reserved':'public',roomId,recipientId:reservedFor?.userId,data:pending.data};sock.current?.emit('image:send',payload,(r:{error?:string})=>{setSendingImage(false);if(r?.error)setError(r.error);else{URL.revokeObjectURL(pending.url);setPending(null)}})}
  async function userAction(action:'reserved'|'private'|'mute'|'block'|'report',person:Participant){setMenuUser(null);if(action==='reserved'){setActiveConversation(null);setReservedFor(person);return}if(action==='private'){sock.current?.emit('private:invite',{invitedUserId:person.userId},(r:{error?:string})=>{if(r.error)setError(r.error);else refreshConversations()});return}if(action==='mute'){await api(`/mutes/${person.userId}`,{method:'POST'});return}if(action==='block'){if(!confirm(`Bloquear ${person.nickname}? Toda interação privada será encerrada.`))return;await api(`/blocks/${person.userId}`,{method:'POST'});setReservedFor(null);if(activeConversation&&other(activeConversation,me!.id).id===person.userId)setActiveConversation(null);refreshConversations();return}const reason=prompt('Motivo da denúncia:');if(reason)await api('/reports',{method:'POST',body:JSON.stringify({reportedUserId:person.userId,reason})});}
  async function respond(invite:Invite,accept:boolean,block=false){sock.current?.emit('private:invite:respond',{conversationId:invite.conversation.id,accept,block},(r:{error?:string})=>{if(r.error)setError(r.error);else{setInvites(v=>v.filter(x=>x.conversation.id!==invite.conversation.id));refreshConversations()}})}
  async function closeConversation(){if(!activeConversation)return;if(confirm('Encerrar esta conversa privada?')){await api(`/private-conversations/${activeConversation.id}/close`,{method:'POST'});setActiveConversation(null);refreshConversations()}}
  async function openSettings(){setBlocked(await api('/blocks'));setSettings(true)}
  async function logout(){await api('/auth/logout',{method:'POST'});nav('/')}
  const activeTitle=activeConversation&&me?other(activeConversation,me.id).profile.nickname:'Conversa Geral';const merged=useMemo(()=>[...currentMessages.map(message=>({type:'message' as const,date:message.createdAt,item:message})),...currentImages.map(image=>({type:'image' as const,date:image.createdAt,item:image}))].sort((a,b)=>+new Date(a.date)-+new Date(b.date)),[currentMessages,currentImages]);
  return <main className="chat"><aside className={`rooms ${roomsDrawer?'open':''}`}><div className="mobile-nav-head"><Link className="brand" to="/">binger<span>.</span></Link><button className="mobile" onClick={()=>setRoomsDrawer(false)}><X/></button></div><div className="room-label">SUA CIDADE</div><button className={`room ${!activeConversation?'active':''}`} onClick={()=>{setActiveConversation(null);setRoomsDrawer(false)}}><span>#</span><div><b>Conversa Geral</b><small>{me?.profile.city.name}</small></div></button><div className="room-label private-label">CONVERSAS PRIVADAS</div><div className="conversation-list">{conversations.map(c=>{const p=me?other(c,me.id):c.participantOne;return <button key={c.id} className={`conversation ${activeConversation?.id===c.id?'active':''}`} onClick={()=>{selectConversation(c);setRoomsDrawer(false)}}><span className="avatar" style={{background:color(p.id)}}>{p.profile.nickname.slice(0,2).toUpperCase()}</span><span><b>{p.profile.nickname}</b><small>{c.status==='PENDING'?(c.requestedById===me?.id?'Convite enviado':'Convite recebido'):'Conversa privada'}</small></span>{c.unreadCount>0&&<em>{c.unreadCount}</em>}</button>})}</div><div className="privacy-note"><ShieldCheck/><div><b>Você está protegido</b><small>Conteúdo privado exige autorização dos dois participantes.</small></div></div><button className="logout" onClick={openSettings}><Settings/> Configurações</button><button className="logout" onClick={logout}><LogOut/> Sair da conta</button></aside>
  <section className="messages"><header><button className="mobile" onClick={()=>setRoomsDrawer(true)}><Menu/></button><div>{activeConversation&&<span className="private-kicker">CONVERSA PRIVADA</span>}<h1>{activeTitle}</h1><p><i/> {activeConversation?'Somente vocês dois':`Ao vivo em ${me?.profile.city.name}`}</p></div>{activeConversation&&<div className="header-actions"><button onClick={closeConversation}>Encerrar conversa</button><button className="icon-danger" onClick={()=>me&&userAction('block',{userId:other(activeConversation,me.id).id,nickname:other(activeConversation,me.id).profile.nickname,ageRange:other(activeConversation,me.id).profile.ageRange})}><Ban/></button></div>}<button className="mobile" onClick={()=>setDrawer(true)}><Users/><span>{people.length}</span></button></header>
  {invites.map(invite=><div className="invite-banner" key={invite.conversation.id}><span><b>{invite.from.profile.nickname}</b> quer abrir uma conversa privada.</span><button onClick={()=>respond(invite,true)}>Aceitar</button><button onClick={()=>respond(invite,false)}>Recusar</button><button onClick={()=>respond(invite,false,true)}>Bloquear</button></div>)}
  {!activeConversation&&<div className="warning"><ShieldCheck/> Não compartilhe telefone, endereço, documentos ou informações financeiras.</div>}
  <div className="stream" aria-live="polite">{merged.length===0&&<div className="empty"><h2>A conversa está só começando.</h2><p>Seja gentil e dê o primeiro oi.</p></div>}{merged.map(entry=>entry.type==='image'?<article className={entry.item.sender.id===me?.id?'mine':''} key={entry.item.id}><Avatar user={entry.item.sender}/><div><Meta user={entry.item.sender} date={entry.item.createdAt}/><img className="temporary-image" src={entry.item.url} alt="Imagem temporária enviada na conversa"/><small className="temporary-label">Imagem temporária</small></div></article>:<MessageView key={entry.item.id} message={entry.item} me={me} shown={shownBlocked.has(entry.item.id)} onShow={()=>setShownBlocked(v=>new Set(v).add(entry.item.id))} onMenu={user=>setMenuUser({userId:user.id,nickname:user.profile.nickname,ageRange:user.profile.ageRange})}/>)}</div>
  {error&&<div className="chat-error" role="status">{error}</div>}{reservedFor&&!activeConversation&&<div className="reserved-banner"><Lock/> <span>Mensagem reservada para <b>{reservedFor.nickname}</b></span><button onClick={()=>setReservedFor(null)}><X/> Cancelar</button></div>}{pending&&<div className="image-preview"><img src={pending.url}/><div><b>Imagem pronta · {Math.ceil(pending.size/1024)} KB</b><small>Imagem temporária — desaparece ao atualizar a página</small></div><button onClick={()=>{URL.revokeObjectURL(pending.url);setPending(null)}}><Trash2/></button><button className="send-image" disabled={sendingImage} onClick={sendImage}>{sendingImage?'Enviando…':'Enviar imagem'}</button></div>}
  <form className="composer" onSubmit={send}><input ref={fileRef} className="sr-only" type="file" accept="image/jpeg,image/png,image/webp" onChange={chooseImage}/><button type="button" className="image-button" aria-label="Adicionar imagem temporária" onClick={()=>fileRef.current?.click()}><ImagePlus/></button><label className="sr-only" htmlFor="message">Mensagem</label><input id="message" name="message" maxLength={500} placeholder={activeConversation?`Mensagem privada para ${activeTitle}`:reservedFor?`Mensagem reservada para ${reservedFor.nickname}`:'Escreva uma mensagem…'} autoComplete="off"/><button aria-label="Enviar mensagem"><Send/></button></form></section>
  <aside className={`participants ${drawer?'open':''}`}><header><div><b>Na sala agora</b><span>{people.length} participante{people.length===1?'':'s'}</span></div><button className="mobile" onClick={()=>setDrawer(false)}><X/></button></header><div className="people">{people.map(p=><button key={p.userId} className={p.userId===me?.id?'self':''} onClick={()=>p.userId!==me?.id&&setMenuUser(p)}><span className="avatar" style={{background:color(p.userId)}}>{p.nickname.slice(0,2).toUpperCase()}</span><span><b>{p.nickname}{p.userId===me?.id?' (você)':''}</b><small>{p.ageRange} · online</small></span></button>)}</div><div className="invite-note">Selecione alguém para enviar uma mensagem reservada ou abrir uma conversa privada.</div></aside>
  {menuUser&&<div className="user-menu-backdrop" onClick={()=>setMenuUser(null)}><div className="user-menu" onClick={e=>e.stopPropagation()}><header><Avatar user={{id:menuUser.userId,profile:{nickname:menuUser.nickname,ageRange:menuUser.ageRange,city:{name:''}}}}/><div><b>{menuUser.nickname}</b><small>{menuUser.ageRange}</small></div><button onClick={()=>setMenuUser(null)}><X/></button></header><button onClick={()=>userAction('reserved',menuUser)}><Lock/> Enviar mensagem reservada</button><button onClick={()=>userAction('private',menuUser)}><MessageCircle/> Abrir conversa privada</button><button onClick={()=>userAction('mute',menuUser)}><BellOff/> Silenciar</button><button className="danger" onClick={()=>userAction('block',menuUser)}><Ban/> Bloquear usuário</button><button onClick={()=>userAction('report',menuUser)}><Flag/> Denunciar usuário</button></div></div>}
  {settings&&<div className="modal-backdrop"><section className="settings-modal"><header><h2>Usuários bloqueados</h2><button onClick={()=>setSettings(false)}><X/></button></header>{blocked.length===0?<p>Nenhum usuário bloqueado.</p>:blocked.map(item=><div className="blocked-row" key={item.id}><Avatar user={item.user}/><b>{item.user.profile.nickname}</b><button onClick={async()=>{await api(`/blocks/${item.user.id}`,{method:'DELETE'});setBlocked(v=>v.filter(x=>x.id!==item.id))}}>Desbloquear</button></div>)}</section></div>}</main>;
}

function Avatar({user}:{user:User}){return <div className="avatar" style={{background:color(user.id)}}>{user.profile.nickname.slice(0,2).toUpperCase()}</div>}
function Meta({user,date,actions}:{user:User;date:string;actions?:()=>void}){return <div className="meta"><b>{user.profile.nickname}</b><span>{user.profile.ageRange}</span><time>{new Date(date).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}</time>{actions&&<button aria-label="Mais ações" onClick={actions}><MoreVertical/></button>}</div>}
function MessageView({message,me,shown,onShow,onMenu}:{message:Msg;me:User|null;shown:boolean;onShow:()=>void;onMenu:(u:User)=>void}){const user=message.user??message.sender!;const hidden=message.blockedForMe&&!shown;return <article className={user.id===me?.id?'mine':''}><Avatar user={user}/><div><Meta user={user} date={message.createdAt} actions={user.id!==me?.id?()=>onMenu(user):undefined}/>{hidden?<div className="blocked-message"><span>Mensagem de usuário bloqueado</span><button onClick={onShow}>Mostrar esta mensagem</button></div>:<><p>{message.content}</p>{message.scope==='RESERVED'&&<small className="reserved-label"><Lock/> Reservado para {message.recipient?.profile.nickname??'você'}</small>}</>}</div></article>}
